//
//  Auxiliar.swift
//  Aula 6
//
//  Created by Turma02-22 on 13/06/24.
//

import Foundation
import MapKit

struct Location: Identifiable {
    let id = UUID()
    let name: String
    let coordinate: CLLocationCoordinate2D
    let flag: String
    let description: String
}

let locations = [
    Location(name: "Denmark", coordinate: CLLocationCoordinate2D(latitude: 55.69055777997899, longitude: 12.552956499413034), flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/240px-Flag_of_Denmark.svg.png", description: "The unified Kingdom of Denmark emerged in the 8th century AD as a proficient maritime power amid the struggle for control of the Baltic Sea.[2] In 1397, it joined Norway and Sweden to form the Kalmar Union, which persisted until the latter's secession in 1523. The remaining Kingdom of Denmark–Norway endured a series of wars in the 17th century that resulted in further territorial cessions. A surge of nationalist movements in the 19th century were defeated in the First Schleswig War of 1848. The adoption of the Constitution of Denmark on 5 June 1849 ended the absolute monarchy and introduced the current parliamentary system. An industrialised exporter of agricultural produce in the second half of the 19th century, Denmark introduced social and labour-market reforms in the early 20th century, which formed the basis for the present welfare state model and advanced mixed economy. Denmark remained neutral during World War I; Danish neutrality was violated in World War II by a rapid German invasion in April 1940. During occupation, a resistance movement emerged in 1943, while Iceland declared independence in 1944; Denmark was liberated after the end of the war in May 1945. In 1973, Denmark, together with Greenland but not the Faroe Islands, became a member of what is now the European Union, but negotiated certain opt-outs, such as retaining its own currency, the krone."),
    Location(name: "Norway", coordinate: CLLocationCoordinate2D(latitude: 59.91516725005244, longitude: 10.727041400147321), flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/1200px-Flag_of_Norway.svg.png", description: "The country shares a long eastern border with Sweden. It is bordered by Finland and Russia to the northeast and the Skagerrak strait to the south. Norway has an extensive coastline facing the North Atlantic Ocean and the Barents Sea. Harald V of the House of Glücksburg is the current King of Norway. Jonas Gahr Støre has been Prime Minister of Norway since 2021. As a unitary state with a constitutional monarchy, Norway divides state power between the parliament, the cabinet, and the supreme court, as determined by the 1814 constitution. The unified kingdom of Norway was established in 872 as a merger of petty kingdoms and has existed continuously for 1,151–1,152 years. From 1537 to 1814, Norway was part of Denmark–Norway, and, from 1814 to 1905, it was in a personal union with Sweden. Norway was neutral during the First World War, and in the Second World War until April 1940 when it was invaded and occupied by Nazi Germany until the end of the war."),
    Location(name: "Iceland", coordinate: CLLocationCoordinate2D(latitude: 64.14178857334137, longitude: -21.926430182832995), flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/250px-Flag_of_Iceland.svg.png", description: "According to the ancient manuscript Landnámabók, the settlement of Iceland began in 874 AD when the Norwegian chieftain Ingólfr Arnarson became the first permanent settler on the island.[15] In the following centuries, Norwegians, and to a lesser extent other Scandinavians, immigrated to Iceland, bringing with them thralls (i.e., slaves or serfs) of Gaelic origin. The island was governed as an independent commonwealth under the native parliament, the Althing, one of the world's oldest functioning legislative assemblies. Following a period of civil strife, Iceland acceded to Norwegian rule in the 13th century. In 1397, Iceland followed Norway's integration into the Kalmar Union along with the kingdoms of Denmark and Sweden, coming under de facto Danish rule following its dissolution in 1523. The Danish kingdom introduced Lutheranism by force in 1550,[16] and Iceland was formally ceded to Denmark in 1814 by the Treaty of Kiel."),
    Location(name: "Sweden", coordinate: CLLocationCoordinate2D(latitude: 59.330514113573685, longitude: 18.07051183703664), flag: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Flag_of_Sweden.svg/2560px-Flag_of_Sweden.svg.png", description: "Sweden has been inhabited since prehistoric times, c. 12,000 BC. The inhabitants emerged into history as the Geats (Swedish: Götar) and Swedes (Svear) and constituted the sea peoples known as the Norsemen. A unified Swedish state emerged during the late 10th century. In 1397, Sweden joined Norway and Denmark to form the Scandinavian Kalmar Union,[10] which Sweden left in 1523. When Sweden became involved in the Thirty Years' War on the Protestant side, an expansion of its territories began, forming the Swedish Empire, which remained one of the great powers of Europe until the early 18th century. During this era Sweden controlled much of the Baltic Sea. Most of the conquered territories outside the Scandinavian Peninsula were lost during the 18th and 19th centuries. The eastern half of Sweden, present-day Finland, was lost to Imperial Russia in 1809. The last war in which Sweden was directly involved was in 1814, when Sweden by military means forced Norway into a personal union, a union which lasted until 1905."),
    Location(name: "Finland", coordinate: CLLocationCoordinate2D(latitude: 60.1732987531189, longitude: 24.925246854954572), flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/2560px-Flag_of_Finland.svg.png", description: "Finland was first settled around 9000 BC after the last Ice Age.[14] During the Stone Age, various cultures emerged, distinguished by different styles of ceramics. The Bronze Age and Iron Ages were marked by contacts with other cultures in Fennoscandia and the Baltic region.[15] From the late 13th century, Finland became part of the Swedish Empire as a result of the Northern Crusades. In 1809, as a result of the Finnish War, Finland was captured from Sweden and became a Grand Duchy of Finland, an autonomous state ruled by the Russian Empire. During this period, Finnish art flourished and the idea of full independence began to take hold. In 1906, Finland became the first European state to grant universal suffrage, and the first in the world to give all adult citizens the right to run for public office.[16][note 2] Following the Russian Revolution of 1917, Finland declared its full independence. In 1918 the young nation was divided by the Finnish Civil War. During World War II, Finland fought against the Soviet Union in the Winter War and the Continuation War, and later against Nazi Germany in the Lapland War. As a result, it lost parts of its territory but retained its independence. Finland remained a largely agricultural country until the 1950s. After World War II, it industrialised quickly and established an advanced economy, with a welfare state built on the Nordic model. This allowed the country to experience overall prosperity and high per capita income.[17] During the Cold War, Finland officially embraced a policy of neutrality. Since then, it has become a member of the European Union in 1995, the Eurozone in 1999, and NATO in 2023.")
]
